version: 2
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              sudo apt-get -y install wget zip unzip
      - run:
          name: Download Godot 3.1
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.1/Godot_v3.1-stable_linux_headless.64.zip
              unzip Godot_v3.1-stable_linux_headless.64.zip
              mv Godot_v3.1-stable_linux_headless.64 godot
              chmod +x godot
      - run:
          name: Download Godot 3.1 Export Templates
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.1/Godot_v3.1-stable_export_templates.tpz
              mkdir -p ~/.local/share/godot/templates
              unzip Godot_v3.1-stable_export_templates.tpz -d ~/.local/share/godot/templates
              mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.1.stable
      - run:
          name: Download butler
          command: |
              wget -q -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
              unzip butler.zip
              chmod +x butler
      - run:
          name: Export win64 build
          command: |
              mkdir -p win64
              ./godot --export win64 project.godot "win64/NGP.exe"
      - run:
          name: Upload win64 build
          command: if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push win64 kentaro22/NGP:win-64bit; fi
      - run:
          name: Export linux64 build
          command: |
              mkdir -p linux64
              ./godot --export linux project.godot "linux64/NGP"
      - run:
          name: Upload linux64 build
          command: if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push linux64 kentaro22/NGP:linux-64bit; fi

      - run:
          name: Export mac build
          command: |
              ./godot --export macOS project.godot "NGP-mac"
              mv NGP-mac NGP-mac.zip
      - run:
          name: Upload mac build
          command: if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push NGP-mac.zip kentaro22/NGP:mac; fi
      - run:
          name: Export Web build
          command: |
              ./godot --export web project.godot "web"
              mv web web.zip
      - run:
          name: Upload mac build
          command: if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push web.zip kentaro22/NGP:web; fi