version: 2
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              sudo apt-get -y install wget zip unzip
      - run:
          name: Download Godot 3.1
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.1/Godot_v3.1-stable_linux_headless.64.zip
              unzip Godot_v3.1-stable_linux_headless.64.zip
              mv Godot_v3.1-stable_linux_headless.64 godot
              chmod +x godot
      - run:
          name: Download Godot 3.1 Export Templates
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.1/Godot_v3.1-stable_export_templates.tpz
              mkdir -p ~/.local/share/godot/templates
              unzip Godot_v3.1-stable_export_templates.tpz -d ~/.local/share/godot/templates
              mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.1.stable
      - run:
          name: Export web build
          command: |
              mkdir -p web
              ./godot --export web project.godot "win64/ngp.html"